# Generated by Django 5.1.3 on 2024-12-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mesaj", models.CharField(max_length=255)),
                ("time_start", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("time_end", models.CharField(max_length=100)),
                ("happy", models.CharField(max_length=100)),
            ],
        ),
    ]
