# Generated by Django 5.1.3 on 2024-12-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="histogram",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
