# Generated by Django 5.1.3 on 2024-12-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0003_person_histogram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="histogram",
        ),
    ]
